### ISSUE TITLE
Regression in debian obs_scm builds because of b2b0430

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-build#830] opened 2022-06-10 16:23 UTC
Since the deployment of tag 20220531 the [darktable master snapshot][1] builds are failing.

I started bisecting this issue going from tag 20220429. Afterwards i tested with HEAD from master and [b2b0430][2] by @ila-embsys  reverted. that fixes the build as well.

[1]: https://build.opensuse.org/package/show/graphics:darktable:master/darktable
[2]: https://github.com/openSUSE/obs-build/pull/760

**Comment by ila-embsys** [comment] 2022-06-10 21:57
Thanks for the feedback!

The 'debtransform' tool had ignored the 'Format' tag in *.dsc file and had always interpreted it as 'Version 1.0' before the b2b0430 merged. Try to change into *.dsc the value of the 'Format' tag from '3.0 (quilt)' to '1.0' to get previous behaviour.

Here is [the fixed build](https://build.opensuse.org/package/show/home:ila.embsys:branches:graphics:darktable:master/darktable).

**Comment by darix** [comment] 2022-06-10 23:27
well the point is more that we would need to announce that breaking change. as the current code is not drop in.

or even better, fix the code that it wouldnt break existing packages.

**Comment by ila-embsys** [comment] 2022-06-11 00:55
I think I have understood where the problem is.

In the building's log 'darktable' package, the actual version is '3.9.0' but the build failed with an error because of not found version '2.4.0'.

The only place where I found this version referred to is the last entry of the 'changelog'.

I don't know why the builder is trying to use this version for the file name. However, previously it could work correctly because during the creation of *.diff file for DSC 1.0, the 'debtransform' was adding an entry to the 'changelog' with the actual version.

I didn't notice such behaviour and didn't provide for DSC 3.0 the same handling in 'changelog' entries.

**Comment by darix** [comment] 2022-06-11 11:43
without your patch the version number gets patched and it finds the proper tarball. with your patch it is not patched so it looks for an outdated tarball.

**Comment by darix** [comment] 2022-06-11 11:46
maybe this line no longer gets executed: https://github.com/ila-embsys/obs-build/blob/eff348e15368b6b8be80d55f33d673edcd5f2770/build-recipe-dsc#L138

 (i mean the whole patching of changelog file should be in debtransform anyway)

**Comment by munix9** [comment] 2022-06-11 18:31
I have the same problem since recently:
https://build.opensuse.org/project/monitor/home:munix9:unstable

It searches for version 1.7.0\~git20190807+d9746691 although the current version is 1.7.0~git20220611+3ccb02b.

No idea how the service gets to "1.7.0~git20190807+d9746691".

**Comment by ila-embsys** [comment] 2022-06-11 18:57
It's the same combination of facts. "Format: 3.0 (quilt)" in *.dsc and outdated changelod records in "debian.tar.gz".

I am working on changelog patching feature for dsc 3.0 as was done for dsc 1.0.

**Comment by munix9** [comment] 2022-06-11 19:00
Maybe, but why is the old value from debian/changelog used?
I have now manually changed this to the current one once for testing - but this should happen automatically as before.

**Closed** 2022-06-13 12:37 UTC

**Comment by darix** [comment] 2022-06-14 10:03
The fix is now deployed on build.opensuse.org
