### ISSUE TITLE
Package build hangs on Fedora 36 archv7

### ISSUE THREAD

**Issue by lamskoy** [openSUSE/obs-build#894] opened 2022-10-14 16:54 UTC
My package fails to be buit against Fedora 36 - armv7l with strange error

`No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)`

Full log is here: https://build.opensuse.org/package/live_build_log/home:el:php/php81/Fedora_36/armv7l

At same time this package is pretty good with openSUSE_Factory_ARM armv7 target

Please advice
```

[   68s] ### VM INTERACTION START ###
[   68s] Using virtio-serial support
[   68s] linux64 /usr/bin/qemu-system-aarch64 -nodefaults -no-reboot -nographic -vga none -cpu host,aarch64=off -enable-kvm -M virt,accel=kvm,usb=off,gic-version=host -sandbox on -object rng-random,filename=/dev/hwrng,id=rng0 -device virtio-rng-device,rng=rng0 -object iothread,id=io0 -runas qemu -net none -kernel /var/cache/obs/worker/root_6/.mount/boot/kernel -initrd /var/cache/obs/worker/root_6/.mount/boot/initrd -append root=/dev/disk/by-id/virtio-0 rootfstype=ext3 rootflags=data=writeback,nobarrier,commit=150,noatime kvmclock mitigations=off elevator=noop nmi_watchdog=0 rw rd.driver.pre=binfmt_misc oops=panic panic=1 quiet console=hvc0 init=/.build/build -m 1280 -drive file=/var/cache/obs/worker/root_6/root,format=raw,if=none,id=disk,cache=unsafe,aio=io_uring -device virtio-blk-device,iothread=io0,drive=disk,serial=0 -drive file=/var/cache/obs/worker/root_6/swap,format=raw,if=none,id=swap,cache=unsafe,aio=io_uring -device virtio-blk-device,iothread=io0,drive=swap,serial=1 -device virtio-serial,max_ports=2 -device virtconsole,chardev=virtiocon0 -chardev stdio,id=virtiocon0 -chardev socket,id=monitor,server=on,wait=off,path=/var/cache/obs/worker/root_6/root.qemu/monitor -mon chardev=monitor,mode=readline -smp 2
[  374s] 
[  374s] ### WATCHDOG TRIGGERED, KILLING VM ###
[  374s] /var/cache/obs/worker/root_6/root: 19602
[  374s] qemu-system-aarch64: terminating on signal 15 from pid 24871 ()
[  374s] ### VM INTERACTION END ###
[  374s] /var/run/obs/worker/6/build/build-vm: line 554: kill: (19593) - No such process
[  374s] No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)
[  374s] or the build host has a kernel or hardware problem...

gave up after 11 failed build attempts...
```

**Comment by hennevogel** [comment] 2022-10-17 11:50
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by adrianschroeter** [comment] 2022-10-17 11:58
This is caused by using the Step 15.3 kernel as default fallback kernel.

That one has a regression reported here on armv7l https://bugzilla.suse.com/show_bug.cgi?id=1204382

**Closed by adrianschroeter** 2022-10-17 11:58 UTC
